Repository boostcampwm-2024/web19-Clovapatra, pull requests merged in 2024-11, with the labels that each got.

#25 [FE] 방 목록 Header UI 구현
  fe/components.json
  fe/package-lock.json
  fe/package.json
  fe/postcss.config.js
  fe/src/App.tsx
  fe/src/components/ui/button.tsx
  fe/src/index.css
  fe/src/lib/utils.ts
  fe/src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomPage/index.tsx
  fe/tailwind.config.js
  fe/tsconfig.app.json
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feat

#26 [FE] 방 검색 SearchBar 컴포넌트 생성
  fe/src/components/common/SearchBar.tsx
  fe/src/components/ui/input.tsx
  fe/src/pages/RoomPage/index.tsx
Labels: design

#27 [FE] 방 제목 및 닉네임 설정 Dialog 컴포넌트 생성
  fe/package-lock.json
  fe/package.json
  fe/src/components/ui/dialog.tsx
  fe/src/components/ui/label.tsx
  fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  fe/src/types/room.ts
Labels: design

#28 chore: 이슈 기반 브랜치 자동 생성 스크립트 작성
  .agt/agt.ps1
  .agt/agt.sh
Labels: chore

#29 chore: PR 자동 생성 기능 추가
  .agt/agt.ps1
  .agt/agt.sh
Labels: chore

#35 [FE] 게임방 컴포넌트 생성 및 Pagination UI 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/components/ui/badge.tsx
  fe/src/components/ui/card.tsx
  fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomPage/RoomList/Pagination.tsx
  fe/src/pages/RoomPage/RoomList/RoomList.tsx
  fe/src/pages/RoomPage/index.tsx
  fe/src/store/useRoomStore.ts
  fe/src/types/room.ts
Labels: feat, design

#36 [FE] Game Page 및 Player 컴포넌트 생성
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.tsx
  fe/src/components/ui/slider.tsx
  fe/src/constants/rules.ts
  fe/src/hooks/usePagination.ts
  fe/src/index.css
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/PlayerList/PlayerList.tsx
  fe/src/pages/GamePage/PlayerList/VolumeBar.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomPage/RoomList/RoomList.tsx
  fe/src/store/useRoomStore.ts
  fe/src/types/player.ts
  fe/src/types/room.ts
Labels: feat, design

#59 [FE] 방 만들기 WebSocket API 요청
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/api/socketApi.ts
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/PlayerList/PlayerList.tsx
  fe/src/pages/GamePage/PlayerList/VolumeBar.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomPage/RoomList/Pagination.tsx
  fe/src/pages/RoomPage/RoomList/RoomList.tsx
  fe/src/store/useRoomStore.ts
  fe/src/types/playerTypes.ts
  fe/src/types/roomTypes.ts
  fe/src/types/socketTypes.ts
Labels: feat

#65 [FE] 사용자는 게임방에 입장할 수 있다.
  fe/src/api/socketApi.ts
  fe/src/pages/RoomPage/RoomList/JoinDialog.tsx
  fe/src/services/gameSocket.ts
  fe/src/store/useRoomStore.ts
  fe/src/types/roomTypes.ts
  fe/src/types/socketTypes.ts
Labels: feat

#69 [BE] 시그널링 서버 구현
  be/signalingServer/package-lock.json
  be/signalingServer/package.json
  be/signalingServer/src/config/app.config.js
  be/signalingServer/src/config/redis.config.js
  be/signalingServer/src/main.js
  be/signalingServer/src/services/redis.service.js
  be/signalingServer/src/services/socket.service.js
  be/signalingServer/src/static/index.html
Labels: feat

#72 fix: GameServer CORS 오류 해결
  be/gameServer/src/main.ts
Labels: fix

#74 [FE] 생성된 방 목록을 가져온다.
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/api/api.ts
  fe/src/api/audioRequest.ts
  fe/src/api/socket.ts
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomPage/index.tsx
  fe/src/store/useRoomStore.ts
  fe/src/types/roomTypes.ts
Labels: feat

#77 [FE][hotfix] 전체 코드 리팩터링
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/api.ts
  fe/src/api/socket.ts
  fe/src/hooks/usePagination.ts
  fe/src/hooks/useRefreshRooms.ts
  fe/src/pages/GamePage/PlayerList/PlayerList.tsx
  fe/src/pages/GamePage/PlayerList/VolumeBar.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomPage/RoomList/JoinDialog.tsx
  fe/src/pages/RoomPage/RoomList/Pagination.tsx
  fe/src/pages/RoomPage/index.tsx
  fe/src/services/SocketService.ts
  fe/src/services/audioRequest.ts
  fe/src/services/gameSocket.ts
  fe/src/services/signalingSocket.ts
  fe/src/store/useRoomStore.ts
  fe/src/stores/queries/getRoomsQuery.ts
  fe/src/stores/zustand/useRoomStore.ts
  fe/src/types/audioTypes.ts
  fe/src/types/playerTypes.ts
  fe/src/types/roomTypes.ts
Labels: refactor

#79 [FE][hotfix] WebRTC 로직 리팩터링
  fe/README.md
  fe/src/hooks/useGameRoom.ts
  fe/src/hooks/useRoomActions.ts
  fe/src/pages/GamePage/PlayerList/VolumeBar.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/services/gameSocket.ts
  fe/src/services/signalingSocket.ts
Labels: refactor

#81 [BE] 시그널링 서버 오류 수정
  be/signalingServer/.env.sample
  be/signalingServer/src/config/app.config.js
  be/signalingServer/src/config/redis.config.js
  be/signalingServer/src/main.js
  be/signalingServer/src/services/redis.service.js
  be/signalingServer/src/services/socket.service.js
  be/signalingServer/src/static/index.html
Labels: fix

#88 [FE] WebRTC Mesh 방식 구현 해치웠다.
  .DS_Store
  fe/README.md
  fe/src/App.tsx
  fe/src/constants/webRTC.ts
  fe/src/hooks/useGameRoom.ts
  fe/src/hooks/useRoomActions.ts
  fe/src/main.tsx
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomDialog/RoomDialog.tsx
  fe/src/pages/RoomListPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomListPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomListPage/RoomList/JoinDialog.tsx
  fe/src/pages/RoomListPage/RoomList/Pagination.tsx
  fe/src/pages/RoomListPage/RoomList/RoomList.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/services/SocketService.ts
  fe/src/services/audioRequest.ts
  fe/src/services/gameSocket.ts
  fe/src/services/signalingSocket.ts
  fe/src/types/socketTypes.ts
  fe/src/types/webrtcTypes.ts
Labels: fix

#98 [FE] SSE 연동하여 방 목록을 가져온다.
  fe/.gitignore
  fe/README.md
  fe/src/App.tsx
  fe/src/config/env.ts
  fe/src/constants/webRTC.ts
  fe/src/hooks/useRefreshRooms.ts
  fe/src/hooks/useRoomsSSE.ts
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomList/JoinDialog.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/services/gameSocket.ts
  fe/src/services/signalingSocket.ts
  fe/src/stores/queries/getRoomsQuery.ts
Labels: feat

#101 [FE] 사용자는 뒤로가기 또는 방 나가기 버튼 클릭 시 게임방을 나갈 수 있다.
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/components/ui/alert-dialog.tsx
  fe/src/hooks/useBackExit.ts
  fe/src/hooks/useRoomsSSE.ts
  fe/src/pages/GamePage/GameDialog/ExitDialog.tsx
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/PlayerList/PlayerList.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
  fe/src/pages/RoomListPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomListPage/RoomList/RoomList.tsx
  fe/src/services/signalingSocket.ts
Labels: feat, design

#104 [FE] GamePage 새로고침 문제 해결
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/assets/lottie/404.json
  fe/src/components/common/NotFound.tsx
  fe/src/components/common/SearchBar.tsx
  fe/src/hooks/useBackExit.ts
  fe/src/hooks/useReconnect.ts
  fe/src/index.css
  fe/src/main.tsx
  fe/src/pages/GamePage/GameDialog/ExitDialog.tsx
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
  fe/src/pages/RoomListPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomListPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomListPage/RoomList/RoomList.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/services/gameSocket.ts
  fe/src/stores/queries/getCurrentRoomQuery.ts
  fe/tailwind.config.js
Labels: fix, feat

#131 [FE] 방장은 모든 참가자가 준비 완료가 되면 게임을 시작할 수 있다.
  fe/src/pages/GamePage/GameScreen/GameScreen.tsx
  fe/src/pages/GamePage/PlayerList/Player.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/services/gameSocket.ts
  fe/src/types/socketTypes.ts
Labels: feat

#148 [FE] 게임 진행 기능 구현
  fe/README.md
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/hooks/useReconnect.ts
  fe/src/pages/GamePage/GameDialog/KickDialog.tsx
  fe/src/pages/GamePage/GameScreen/GameResult.tsx
  fe/src/pages/GamePage/GameScreen/GameScreen.tsx
  fe/src/pages/GamePage/GameScreen/Lyric.tsx
  fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
  fe/src/pages/GamePage/GameScreen/ReadyScreen.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/services/SocketService.ts
  fe/src/services/gameSocket.ts
  fe/src/services/signalingSocket.ts
  fe/src/services/voiceSocket.ts
  fe/src/stores/zustand/useGameStore.ts
  fe/src/types/socketTypes.ts
Labels: feat, design

#160 [FE] 게임 종료 UI 구현
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/assets/lottie/podium.json
  fe/src/pages/GamePage/GameDialog/ExitDialog.tsx
  fe/src/pages/GamePage/GameScreen/EndScreen.tsx
  fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
  fe/src/services/gameSocket.ts
  fe/src/stores/zustand/useGameStore.ts
  fe/src/types/socketTypes.ts
Labels: feat, design

#161 [FE] 게임방 링크를 통해 게임방에 입장할 수 있다.
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
Labels: feat

#164 [FE] 사용자는 키보드 Enter로 Input을 처리할 수 있다.
  fe/README.md
  fe/src/hooks/useDialogForm.ts
  fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
Labels: feat

#166 [FE] 링크 복사 버튼 및 기능 구현
  fe/src/pages/GamePage/index.tsx
Labels: feat

#169 [FE] 사용자는 방 제목을 검색할 수 있다.
  fe/README.md
  fe/src/components/common/SearchBar.tsx
  fe/src/hooks/useDebounce.ts
  fe/src/pages/GamePage/GameScreen/EndScreen.tsx
  fe/src/pages/GamePage/GameScreen/Lyric.tsx
  fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
  fe/src/stores/queries/searchRoomsQuery.ts
Labels: feat

#178 [FE] 강퇴당한 사용자에게 Dialog를 띄운다.
  fe/src/components/common/CustomAlertDialog.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/services/gameSocket.ts
Labels: feat

#189 [FE] 방 목록 페이지네이션 기능 구현
  fe/README.md
  fe/src/components/common/SearchBar.tsx
  fe/src/constants/rules.ts
  fe/src/hooks/usePagination.ts
  fe/src/hooks/useRoomsSSE.ts
  fe/src/pages/RoomListPage/RoomList/Pagination.tsx
  fe/src/pages/RoomListPage/RoomList/RoomList.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/stores/queries/getRoomsQuery.ts
  fe/src/stores/zustand/useRoomStore.ts
  fe/src/types/roomTypes.ts
Labels: feat

#194 [FE] 방 제목, 사용자 닉네임 유효성 검증 UI 구현
  fe/README.md
  fe/index.html
  fe/public/favicon.png
  fe/public/vite.svg
  fe/src/hooks/useFormValidation.ts
  fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
  fe/src/services/gameSocket.ts
  fe/src/utils/validator.ts
Labels: feat, design

#206 [FE] UI 수정
  fe/index.html
  fe/public/favicon.png
  fe/src/assets/images/angry-pepe.png
  fe/src/assets/lottie/404.json
  fe/src/assets/react.svg
  fe/src/components/common/NotFound.tsx
  fe/src/components/game/PitchVisualizer.tsx
  fe/src/components/ui/dialog.tsx
  fe/src/components/ui/slider.tsx
  fe/src/hooks/useFormValidation.ts
  fe/src/index.css
  fe/src/pages/GamePage/GameScreen/EndScreen.tsx
  fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
  fe/src/pages/GamePage/GameScreen/ReadyScreen.tsx
  fe/src/pages/GamePage/PlayerList/PlayerList.tsx
  fe/src/pages/GamePage/PlayerList/VolumeBar.tsx
  fe/src/pages/GamePage/index.tsx
  fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
  fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
  fe/src/pages/RoomListPage/RoomHeader/RoomHeader.tsx
  fe/src/pages/RoomListPage/RoomList/GameRoom.tsx
  fe/src/pages/RoomListPage/RoomList/RoomList.tsx
  fe/src/pages/RoomListPage/index.tsx
  fe/src/utils/validator.ts
  fe/tailwind.config.js
Labels: fix, design

#208 [FE] 각 게임 모드 음정 또는 점수 표시
  fe/README.md
  fe/src/pages/GamePage/GameScreen/GameResult.tsx
  fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
  fe/src/types/socketTypes.ts
Labels: fix, design
